In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris

In [3]:
from sklearn.model_selection import train_test_split

In [4]:
X,y=load_iris(return_X_y=True)

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3 , random_state=0)

In [8]:
from sklearn.naive_bayes import GaussianNB

In [9]:
gnb=GaussianNB()

In [10]:
gnb.fit(X_train,y_train)

GaussianNB()

In [11]:
y_pred = gnb.predict(X_test)

In [12]:
from sklearn.metrics import accuracy_score,classification_report ,confusion_matrix

In [13]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



# Dataset tips 

In [14]:
sns.load_dataset('tips')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [15]:
df = sns.load_dataset('tips')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [17]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [18]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [19]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [20]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

# feature Encoding
- If feature are present in binary form then use **LAbel encoding** here [time, smoker, sex are binary outcomes so use LAble encoding]
- If feature are present more than two then use **OneHot Encoding** [ day feature consit of more than two outcome so use OneHot Encoding)

In [21]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [22]:
X = df[['total_bill', 'tip', 'sex', 'smoker', 'day','size']]
y = df['time']

In [23]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2 ,random_state=0)

In [24]:
X_train.head()

total_bill   tip   sex smoker   day  size
7         26.88  3.12  Male     No   Sun     4
83        32.68  5.00  Male    Yes  Thur     2
176       17.89  2.00  Male    Yes   Sun     2
106       20.49  4.06  Male    Yes   Sat     2
156       48.17  5.00  Male     No   Sun     6

# Lable Encoding

In [25]:
from sklearn.preprocessing import LabelEncoder

In [26]:
# Initialize LabelEncoders
le_sex = LabelEncoder()
le_smoker = LabelEncoder()
le_time = LabelEncoder()

In [27]:
# Fit the LabelEncoders on the training data
X_train['sex'] = le_sex.fit_transform(X_train['sex'])
X_train['smoker'] = le_smoker.fit_transform(X_train['smoker'])
y_train = le_time.fit_transform(y_train)

In [28]:
# Transform the test data using the fitted LabelEncoders
X_test['sex'] = le_sex.transform(X_test['sex'])
X_test['smoker'] = le_smoker.transform(X_test['smoker'])
y_test = le_time.transform(y_test)

In [29]:
X_train.head()

total_bill   tip  sex  smoker   day  size
7         26.88  3.12    1       0   Sun     4
83        32.68  5.00    1       1  Thur     2
176       17.89  2.00    1       1   Sun     2
106       20.49  4.06    1       1   Sat     2
156       48.17  5.00    1       0   Sun     6

# OneHot Encoding for More than two outcome -- columnTransformer

In [30]:
# OneHot Encoding for More than two outcome -- columnTransformer 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('onehot',OneHotEncoder(drop='first'),[4])],remainder='passthrough')
ct.fit_transform(X_train)

array([[0., 1., 0., ..., 1., 0., 4.],
       [0., 0., 1., ..., 1., 1., 2.],
       [0., 1., 0., ..., 1., 1., 2.],
       ...,
       [0., 0., 1., ..., 0., 0., 2.],
       [0., 1., 0., ..., 1., 0., 4.],
       [0., 1., 0., ..., 1., 1., 2.]])

In [31]:
import sys
np.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [32]:
X_test=ct.fit_transform(X_test)

In [33]:
X_test

array([[ 1.  ,  0.  ,  0.  , 17.59,  2.64,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 19.49,  3.51,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.25,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 0.  ,  0.  ,  0.  , 16.27,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  5.75,  1.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  3.08,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.15,  3.5 ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.65,  3.68,  1.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 25.28,  5.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 25.21,  4.29,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.07,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  1.58,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.

In [34]:
X_train

array([[ 0.  ,  1.  ,  0.  , 26.88,  3.12,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.89,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.49,  4.06,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 48.17,  5.  ,  1.  ,  0.  ,  6.  ],
       [ 0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.03,  1.5 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 29.93,  5.07,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 20.69,  2.45,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 14.26,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 12.66,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 27.28,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.81,  3.16,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 21.16,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 25.  ,  3.75,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.

In [35]:
y_train

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [36]:
y_test

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0])

# GaussianNB Model 

In [37]:
from sklearn.naive_bayes import GaussianNB

In [38]:
gnb1 =GaussianNB()

In [39]:
gnb1.fit(X_train,y_train)

GaussianNB()

In [40]:
y_pred1 = gnb1.predict(X_test)

In [41]:
from sklearn.metrics import accuracy_score,classification_report ,confusion_matrix

In [42]:
print(confusion_matrix(y_pred1,y_test))
print(accuracy_score(y_pred1,y_test))
print(classification_report(y_pred1,y_test))

[[34  5]
 [ 1  9]]
0.8775510204081632
              precision    recall  f1-score   support

           0       0.97      0.87      0.92        39
           1       0.64      0.90      0.75        10

    accuracy                           0.88        49
   macro avg       0.81      0.89      0.83        49
weighted avg       0.90      0.88      0.88        49

